version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my-network  # Определение сети для использования алиаса
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/redilab  # Использование алиаса
    networks:
      - my-network  # Подключение к той же сети, что и MongoDB

networks:
  my-network:
    driver: bridge

volumes:
  mongo_data:
