version: '3'
services:
  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017/redilab
    depends_on:
      - mongo
    volumes:
      - mongo_data:/data/db

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: redilab
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
