version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network

  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/redilab
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo_data:
